import { MetadataRoute } from 'next';

const BASE_URL = process.env.BASE_URL as string;

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Seven Consulting Training | Liderando com segurança há anos',
    short_name: 'Seven Consulting Training',
    description:
      'Desenvolvendo soluções em treinamentos de Segurança do Trabalho, Licenciamento Ambiental e programas como PGRO, LTCAT, estudos de viabilidade (LP, LI, LO), etc.',
    start_url: BASE_URL + '/',
    display: 'standalone',
    lang: 'pt-BR',
    background_color: '#fff',
    categories: [
      'education',
      'environment',
      'consulting',
      'segurança e saúde no trabalho',
      'educação',
      'consultoria de meio ambiente',
      'consultoria',
      'segurança',
      'saúde',
      'trabalho',
      'treinamentos',
      'capacitação',
      'normas regulamentadoras',
      'NR 01 - Disposições Gerais e Gerenciamento de Riscos Ocupacionais',
      'NR 02 - Inspeção Prévia',
      'NR 03 - Embargo e Interdição',
      'NR 04 - Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho',
      'NR 05 - Comissão Interna de Prevenção de Acidentes (CIPA)',
      'NR 06 - Equipamentos de Proteção Individual (EPI)',
      'NR 07 - Programa de Controle Médico de Saúde Ocupacional (PCMSO)',
      'NR 08 - Edificações',
      'NR 09 - Avaliação e Controle das Exposições Ocupacionais a Agentes Físicos, Químicos e Biológicos',
      'NR 10 - Segurança em Instalações e Serviços em Eletricidade',
      'NR 11 - Segurança na Operação de Elevadores, Guindastes, Transportadores Industriais e Máquinas Transportadoras',
      'NR 12 - Segurança no Trabalho em Máquinas e Equipamentos',
      'NR 13 - Caldeiras, Vasos de Pressão e Tubulações',
      'NR 14 - Forno',
      'NR 15 - Atividades e Operações Insalubres',
      'NR 16 - Atividades e Operações Perigosas',
      'NR 17 - Ergonomia',
      'NR 18 - Condições de Trabalho e Meio Ambiente na Indústria da Construção',
      'NR 19 - Explosivos',
      'NR 20 - Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis',
      'NR 21 - Trabalho a Céu Aberto',
      'NR 22 - Segurança e Saúde Ocupacional na Mineração',
      'NR 23 - Proteção Contra Incêndios',
      'NR 24 - Condições Sanitárias e de Conforto nos Locais de Trabalho',
      'NR 25 - Resíduos Industriais',
      'NR 26 - Sinalização de Segurança',
      'NR 27 - Registro Profissional do Técnico de Segurança do Trabalho no MTB',
      'NR 28 - Fiscalização e Penalidades',
      'NR 29 - Segurança e Saúde no Trabalho Portuário',
      'NR 30 - Segurança e Saúde no Trabalho Aquaviário',
      'NR 31 - Segurança e Saúde no Trabalho na Agricultura, Pecuária, Silvicultura, Exploração Florestal e Aquicultura',
      'NR 32 - Segurança e Saúde no Trabalho em Estabelecimentos de Saúde',
      'NR 33 - Segurança e Saúde nos Trabalhos em Espaços Confinados',
      'NR 34 - Condições e Meio Ambiente de Trabalho na Indústria da Construção e Reparação Naval',
      'NR 35 - Trabalho em Altura',
      'NR 36 - Segurança e Saúde no Trabalho em Empresas de Abate e Processamento de Carnes e Derivados',
      'NR 37 - Segurança e Saúde em Plataformas de Petróleo',
      'NR 38 - Segurança e Saúde no Trabalho em Serviços de Limpeza Urbana',
      'sst',
      'maricá',
      'marica',
      'brasil',
      'brazil',
      'rio de janeiro',
      'rj',
      'br',
      'niterói',
      'segurança',
      'qualidade',
    ],
    theme_color: '#14b8a6',
    icons: [
      {
        src: '/favicon/favicon.ico',
        sizes: 'any',
        type: 'image/x-icon',
      },
      {
        src: '/favicon/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/favicon/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
      {
        src: '/favicon/favicon-16x16.png',
        sizes: '16x16',
        type: 'image/png',
      },
      {
        src: '/favicon/favicon-32x32.png',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        src: '/favicon/apple-touch-icon.png',
        sizes: 'any',
        type: 'image/png',
      },
    ],
  };
}
