import { Metadata } from 'next';

const BASE_URL = process.env.BASE_URL as string;

export const metadata: Metadata = {
  creator: 'Miguel Rocha',
  robots: { index: true, follow: true },
  title: 'Seven Consulting Training | Liderando com segurança há anos',
  applicationName: 'Seven Consulting Training | Liderando com segurança há anos',
  manifest: BASE_URL + '/manifest.webmanifest',
  description:
    'Desenvolvendo soluções em treinamentos de Segurança do Trabalho, Licenciamento Ambiental e programas como PGRO, LTCAT, estudos de viabilidade (LP, LI, LO), etc.',
  category:
    'segurança e saúde no trabalho, consultoria, meio ambiente, treinamentos, capacitação, normas regulamentadoras',
  keywords: [
    'education',
    'environment',
    'consulting',
    'segurança e saúde no trabalho',
    'educação',
    'consultoria de meio ambiente',
    'consultoria',
    'segurança',
    'saúde',
    'trabalho',
    'treinamentos',
    'capacitação',
    'normas regulamentadoras',
    'NR 01 - Disposições Gerais e Gerenciamento de Riscos Ocupacionais',
    'NR 02 - Inspeção Prévia',
    'NR 03 - Embargo e Interdição',
    'NR 04 - Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho',
    'NR 05 - Comissão Interna de Prevenção de Acidentes (CIPA)',
    'NR 06 - Equipamentos de Proteção Individual (EPI)',
    'NR 07 - Programa de Controle Médico de Saúde Ocupacional (PCMSO)',
    'NR 08 - Edificações',
    'NR 09 - Avaliação e Controle das Exposições Ocupacionais a Agentes Físicos, Químicos e Biológicos',
    'NR 10 - Segurança em Instalações e Serviços em Eletricidade',
    'NR 11 - Segurança na Operação de Elevadores, Guindastes, Transportadores Industriais e Máquinas Transportadoras',
    'NR 12 - Segurança no Trabalho em Máquinas e Equipamentos',
    'NR 13 - Caldeiras, Vasos de Pressão e Tubulações',
    'NR 14 - Forno',
    'NR 15 - Atividades e Operações Insalubres',
    'NR 16 - Atividades e Operações Perigosas',
    'NR 17 - Ergonomia',
    'NR 18 - Condições de Trabalho e Meio Ambiente na Indústria da Construção',
    'NR 19 - Explosivos',
    'NR 20 - Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis',
    'NR 21 - Trabalho a Céu Aberto',
    'NR 22 - Segurança e Saúde Ocupacional na Mineração',
    'NR 23 - Proteção Contra Incêndios',
    'NR 24 - Condições Sanitárias e de Conforto nos Locais de Trabalho',
    'NR 25 - Resíduos Industriais',
    'NR 26 - Sinalização de Segurança',
    'NR 27 - Registro Profissional do Técnico de Segurança do Trabalho no MTB',
    'NR 28 - Fiscalização e Penalidades',
    'NR 29 - Segurança e Saúde no Trabalho Portuário',
    'NR 30 - Segurança e Saúde no Trabalho Aquaviário',
    'NR 31 - Segurança e Saúde no Trabalho na Agricultura, Pecuária, Silvicultura, Exploração Florestal e Aquicultura',
    'NR 32 - Segurança e Saúde no Trabalho em Estabelecimentos de Saúde',
    'NR 33 - Segurança e Saúde nos Trabalhos em Espaços Confinados',
    'NR 34 - Condições e Meio Ambiente de Trabalho na Indústria da Construção e Reparação Naval',
    'NR 35 - Trabalho em Altura',
    'NR 36 - Segurança e Saúde no Trabalho em Empresas de Abate e Processamento de Carnes e Derivados',
    'NR 37 - Segurança e Saúde em Plataformas de Petróleo',
    'NR 38 - Segurança e Saúde no Trabalho em Serviços de Limpeza Urbana',
    'sst',
    'maricá',
    'marica',
    'brasil',
    'brazil',
    'rio de janeiro',
    'rj',
    'br',
    'niterói',
    'segurança',
    'qualidade',
    'segurança no trabalho',
    'segurança do trabalho normas',
    'segurança do trabalho e saúde ocupacional',
    'saúde ocupacional',
    'médico do trabalho',
    'exame ocupacional',
    'prevenção de acidentes de trabalho',
    'como prevenir acidentes de trabalho',
    'dicas de segurança no trabalho',
    'NR 5 CIPA',
    'NR 6 EPI',
    'NR 9 PPRA',
    'NR 17 ergonomia',
    'NR 10 segurança em eletricidade',
    'NR 35 trabalho em altura',
    'exame admissional',
    'exame demissional',
    'exame periódico',
    'exame de retorno ao trabalho',
    'treinamento de segurança no trabalho',
    'curso de NR 10',
    'curso de NR 35',
    'treinamento de brigada de incêndio',
    'laudo de insalubridade',
    'laudo de periculosidade',
    'laudo ergonômico',
    'PCMSO',
    'programa de controle médico de saúde ocupacional',
    'implantação de PCMSO',
    'PPRA',
    'programa de prevenção de riscos ambientais',
    'elaboração de PPRA',
    'EPI',
    'compra de EPI',
    'uso de EPI',
    'tipos de EPI',
    'consultoria em segurança do trabalho',
    'empresa de segurança do trabalho',
    'serviços de consultoria em segurança do trabalho',
    'inspeção de segurança no trabalho',
    'inspeção de segurança',
    'auditoria de segurança do trabalho',
    'mapeamento de riscos',
    'identificação de riscos no trabalho',
    'gestão de riscos ocupacionais',
    'licença sanitária',
    'certificado de aprovação de EPI',
    'certificação de segurança do trabalho',
    'análise de risco',
    'programa de ergonomia',
    'treinamento de primeiros socorros',
    'segurança contra incêndio',
    'programa de gestão de segurança',
    'investigação de acidentes',
    'auditoria de conformidade',
    'controle de risco químico',
    'segurança em máquinas e equipamentos',
    'plano de emergência',
    'gestão de EPIs',
    'monitoramento de saúde',
    'higiene ocupacional',
    'avaliação de riscos ambientais',
    'programa de prevenção de doenças ocupacionais',
    'treinamento em NR 12',
    'treinamento em NR 18',
    'curso de NR 20',
    'treinamento de segurança em espaço confinado',
    'segurança no transporte de produtos perigosos',
    'controle de ruído ocupacional',
    'segurança em trabalhos a quente',
    'programa de proteção respiratória',
    'gestão de saúde e segurança ocupacional',
    'normas de segurança no trabalho',
    'cursos de segurança no trabalho online',
    'segurança do trabalho em canteiros de obra',
    'segurança no uso de produtos químicos',
    'gestão de saúde e segurança no trabalho',
    'análise de acidentes de trabalho',
  ],
  openGraph: {
    title: 'Seven Consulting Training | Liderando com segurança há anos',
    description:
      'Desenvolvendo soluções em treinamentos de Segurança do Trabalho, Licenciamento Ambiental e programas como PGRO, LTCAT, estudos de viabilidade (LP, LI, LO), etc.',
    url: BASE_URL,
    siteName: 'Seven Consulting Training',
    locale: 'pt_BR',
    type: 'website',
    emails: [
      'geral@sevenconsultingtraining.com.br',
      'contato@sevenconsultingtraining.com.br',
      'gerlain.lopes@sevenconsultingtraining.com.br',
      'lavinia.lopes@sevenconsultingtraining.com.br',
    ],
    images: [
      {
        url: BASE_URL + '/images/white-bg-logo-margin.png',
        width: 512,
        height: 226,
        alt: 'Seven Consulting Training | Liderando com segurança há anos',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Seven Consulting Training | Liderando com segurança há anos',
    description:
      'Desenvolvendo soluções em treinamentos de Segurança do Trabalho, Licenciamento Ambiental e programas como PGRO, LTCAT, estudos de viabilidade (LP, LI, LO), etc.',
    images: [BASE_URL + '/images/white-bg-logo-margin.png'],
  },
};
